### ISSUE TITLE
Quiz HTML

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/action-series-quizzes#3]
https://github.com/byuitechops/action-series-quizzes/blob/cec8d400a8a2f6d2ee5bfe2334f91f6623854d59/template-quizzes.js#L98-L104

The quiz descriptions can contain HTML, even though the docs don't show it. I believe it is the "description" property.
https://canvas.instructure.com/doc/api/quizzes.html

**Comment by sethchilders92** [comment]
Nice catch! Done.
